### PR TITLE
add alt prop to the image

### LINKED ISSUE #10: alt prop warning in build
Let's fix this:

```
WARNING in src/App.tsx
  Line 61:19:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
```

This is the logo-- I think we can count that as "decorative" and use an empty string.

### PR DESCRIPTION
**Pull request by coder-abdo**
Fixes #10

adding `alt` attribute to the `img` element to enhance the accessibility and the Semantic UI

### CODE REVIEW

**Comment by krancour** [comment]
@coder-abdo thanks for the contribution!

Sorry to nitpick, but I'm reluctant to go with "company logo" just because we're not really a company.

Let's go with "Brigade Logo". Sound ok?

**Comment by coder-abdo** [comment]
that is great and it is fit to the project nicely

**Comment by krancour** [comment]
@coder-abdo it looks like you amended the commit after our previous conversation, but I still don't see the change we discussed. Did something go wrong?

**Comment by coder-abdo** [comment]
I changed here
https://github.com/brigadecore/brigade-dashboard/pull/28
have a look and tell me if I did it correctly.
thanks in advance

**Pull request closed without merging**
