### PR TITLE
replace hacky make targets with tilt

### PR DESCRIPTION
**Pull request by krancour**
Signed-off-by: Kent Rancourt <kent.rancourt@microsoft.com>

### CODE REVIEW

**Review by vdice — COMMENTED** [review]
@krancour I picked this PR at random as the first tilt test.  However, as someone new to running Tilt, I'm unsure where to start.  I don't see a correlating `make` target to run tilt and it doesn't appear there are docs on how to run (or linking to Tilt docs, etc.)  Should we add something to this PR for helping new users get started?

**Comment by krancour** [comment]
> I picked this PR at random as the first tilt test. However, as someone new to running Tilt, I'm unsure where to start. I don't see a correlating make target to run tilt and it doesn't appear there are docs on how to run (or linking to Tilt docs, etc.) Should we add something to this PR for helping new users get started?

My overall plan is that after https://github.com/brigadecore/brigade/pull/1910 is merged, I'll revisit https://github.com/brigadecore/brigade/pull/1908 to make sure everything is well explained for Brigade itself, then I'll update each peripheral with docs that cover any repo-specific steps and link back to Brigade docs for more comprehensive coverage of how all this works.

For each individual peripheral, existing hacking steps are already not documented unfortunately, so merging this likely leaves us no worse off than before and at least we have a plan.

In the meantime, assuming you have kind and a local registry running, `tilt up` is all you need to do.

**Comment by krancour** [comment]
@vdice btw... if you want to try this out, it might be faster to try it with one of the gateways. The dashboard image takes a long time to build because React builds are slow by nature.

**Review by vdice — APPROVED** [review]
I stood up a kind cluster and then ran `tilt up`:

```
$ tilt up
Tilt started on http://localhost:10350/
v0.27.0, built 2022-04-01

(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
Tilt started on http://localhost:10350/
v0.27.0, built 2022-04-01

Initial Build
Loading Tiltfile at: /Users/vdice/go/src/github.com/brigadecore/brigade-dashboard/Tiltfile
local: kubectl version --short
ERROR: Traceback (most recent call last):
  /Users/vdice/go/src/github.com/brigadecore/brigade-dashboard/Tiltfile:48:41: in <toplevel>
Error: key "REACT_APP_BRIGADE_API_ADDRESS" not in environ
```

So should this value be the

**Comment by krancour** [comment]
Same value was required for `make hack`.

Just point it at any API server -- even the dogfood one at `https://api.brigade2.io`

**Pull request merged**
