### PR TITLE
Updating website description

### LINKED ISSUE #5: Web site description needs update
`index.html` currently has this:

```htlm
<meta name="description" content="Web site created using create-react-app"/>
```

This should be updated. I'm not feeling creative, at the moment. "Brigade Dashboard" would suffice, but if whoever grabs this issue wants to propose something else, that's cool, too.

### PR DESCRIPTION
**Pull request by DhairyaBahl**
Fixes #5 

Web site description needs update.

### CODE REVIEW

**Comment by krancour** [comment]
@DhairyaBahl would you possibly be able to amend the commit message with a DCO signoff. I know it's an inconvenience, but CNCF requires it. Ping me on Slack if you need help.

**Review by krancour — APPROVED** [review]
LGTM pending DCO signoff.

**Comment by DhairyaBahl** [comment]
@krancour I think I have also done with amending the DCO Signoff. Kindly check it out.

**Review by krancour — APPROVED** [review]

**Comment by krancour** [comment]
@DhairyaBahl the DCO signoff is all set, but... there's a second type of signature (a cryptographic one) that you had before that's missing now. I think that before when you were making commits through the github UI it added that for you automatically, but you must have swapped to using the CLI (I think?) The CLI needs a little bit of setup in order to provide the same signatures. Let's connect later on Slack and we can sort it out. In the meantime, this PR looks good and I'll waive the requirement for the cryptographic signature for right now.

**Comment by DhairyaBahl** [comment]
> k that before when you were making commits through the github UI it added that for you

No No ! To be honest, I just reverted my commit and then simply changed the commit and force pushed it. No issues. Kindly tell me how to fix this on slack.

**Pull request merged**
